'use client';
import {useEffect,useState} from 'react';
import {supabase} from '../lib/supabase';
import {BookOpen,Users,BookCopy,CalendarClock,TriangleAlert,Star,Tags,Building2,Boxes,History,LayoutDashboard,Search,RefreshCw} from 'lucide-react';
const sections=[['Dashboard','dashboard',LayoutDashboard],['Livros','livros',BookOpen],['Usuários','usuarios',Users],['Empréstimos','emprestimos',BookCopy],['Reservas','reservas',CalendarClock],['Multas','multas',TriangleAlert],['Avaliações','avaliacoes',Star],['Categorias','categorias',Tags],['Editoras','editoras',Building2],['Exemplares','exemplares',Boxes],['Histórico','historico_acoes',History]];
const labels={id:'ID',nome:'Nome',titulo:'Título',autor:'Autor',quantidade:'Qtd.',preco:'Preço',email:'E-mail',usuario:'Usuário',status:'Status',nota:'Nota',valor:'Valor',motivo:'Motivo',acao:'Ação',entidade:'Entidade',comentario:'Comentário',pais:'País',numero_patrimonio:'Patrimônio',estado_conservacao:'Conservação',localizacao:'Localização',data_emprestimo:'Empréstimo',data_devolucao:'Devolução',data_prevista_devolucao:'Prev. devolução',data_reserva:'Reserva',data_expiracao:'Expiração',data_multa:'Data',data_pagamento:'Pagamento',data_avaliacao:'Data',data_acao:'Data'};
const value=v=>v==null?'—':typeof v==='object'?JSON.stringify(v):String(v);
export default function Home(){const[tab,setTab]=useState('dashboard'),[data,setData]=useState({}),[loading,setLoading]=useState(true),[q,setQ]=useState('');
async function load(){setLoading(true);const names=sections.slice(1).map(x=>x[1]);const res=await Promise.all(names.map(async t=>{const{data,error}=await supabase.from(t).select('*').order('id',{ascending:false}).limit(250);return[t,data||[],error]}));setData(Object.fromEntries(res.map(([t,d])=>[t,d])));setLoading(false)}
useEffect(()=>{load()},[]);const rows=data[tab]||[];const filtered=rows.filter(r=>JSON.stringify(r).toLowerCase().includes(q.toLowerCase()));const active=(data.emprestimos||[]).filter(x=>!['devolvido','finalizado'].includes((x.status||'').toLowerCase())).length;const overdue=(data.emprestimos||[]).filter(x=>(x.status||'').toLowerCase()==='atrasado').length;const pending=(data.multas||[]).filter(x=>!['paga','pago'].includes((x.status||'').toLowerCase())).length;
return <main><aside><div className="brand"><div className="logo"><BookOpen/></div><div><b>Biblioteca</b><span>2º DS • ETEC</span></div></div><nav>{sections.map(([n,k,I])=><button key={k} className={tab===k?'active':''} onClick={()=>{setTab(k);setQ('')}}><I size={19}/><em>{n}</em></button>)}</nav><div className="foot">Sistema de Biblioteca<br/><small>Supabase + Next.js</small></div></aside><section className="content"><header><div><p>Sistema de gerenciamento</p><h1>{sections.find(x=>x[1]===tab)?.[0]}</h1></div><button className="refresh" onClick={load}><RefreshCw size={18}/> Atualizar</button></header>{tab==='dashboard'?<><div className="hero"><div><span>VISÃO GERAL</span><h2>Biblioteca DS</h2><p>Controle o acervo, usuários e empréstimos em um só lugar.</p></div><BookOpen size={78}/></div><div className="cards"><Card t="Livros cadastrados" v={(data.livros||[]).length} I={BookOpen}/><Card t="Usuários" v={(data.usuarios||[]).length} I={Users}/><Card t="Empréstimos ativos" v={active} I={BookCopy}/><Card t="Atrasados" v={overdue} I={TriangleAlert}/><Card t="Reservas" v={(data.reservas||[]).length} I={CalendarClock}/><Card t="Multas pendentes" v={pending} I={TriangleAlert}/></div><div className="panel"><h3>Sistema conectado ao Supabase</h3><p>Use o menu para consultar as dez áreas do banco de dados.</p></div></>:<div className="panel"><div className="toolbar"><div><h3>{sections.find(x=>x[1]===tab)?.[0]}</h3><span>{filtered.length} registros</span></div><label><Search size={18}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Pesquisar..."/></label></div>{loading?<div className="empty">Carregando...</div>:filtered.length?<Table rows={filtered}/>:<div className="empty">Nenhum registro encontrado.</div>}</div>}</section></main>}
function Card({t,v,I}){return <div className="card"><div className="cardicon"><I/></div><div><span>{t}</span><strong>{v}</strong></div></div>}
function Table({rows}){const keys=Object.keys(rows[0]||{}).filter(k=>k!=='senha');return <div className="tablewrap"><table><thead><tr>{keys.map(k=><th key={k}>{labels[k]||k.replaceAll('_',' ')}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={r.id??i}>{keys.map(k=><td key={k}>{value(r[k])}</td>)}</tr>)}</tbody></table></div>}